# Generated by Django 5.0 on 2024-01-14 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        ("usermanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.tour"
                    ),
                ),
                (
                    "traveller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usermanagement.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bookings",
                "ordering": ("created_at",),
            },
        ),
    ]
